### ISSUE TITLE
crates.io is out of date

### ISSUE THREAD

**Issue by jbicha** [rust-av/dav1d-rs#102]
Could you push your releases to https://crates.io/crates/dav1d-sys ?

**Comment by lu-zero** [comment]
what is missing for you?

**Comment by jbicha** [comment]
The latest tagged version in this Github repo is 0.10.3 but the [latest version](https://crates.io/crates/dav1d-sys/versions) on crates.io is 0.8.2

**Comment by lu-zero** [comment]
The latest version of dav1d-sys is 0.8.2, the tag is used for the main crate dav1d that is bumped more often.
