### ISSUE TITLE
Need a release

### ISSUE THREAD

**Issue by gdesmott** [rust-av/dav1d-rs#30]
Hi there,

Could we please have a release including https://github.com/rust-av/dav1d-rs/commit/87fe798703932a874d43a1639b200deea06d0155 ? That would save us from shipping different versions of `nom` in our project.

**Comment by lu-zero** [comment]
Sure :) do you need only the -sys crate?

**Comment by gdesmott** [comment]
Well, we'll need an updated version of the `dav1d` crate depending on the new -sys as well :)

**Comment by lu-zero** [comment]
Done. Let me know if it works as intended.

**Comment by gdesmott** [comment]
`cargo deny` is happy again, thank! :+1:

**Comment by lu-zero** [comment]
Great!
