### ISSUE TITLE
Docs are not failing to find dav1d library

### ISSUE THREAD

**Issue by vibhoothi** [rust-av/dav1d-rs#45]
Hi,

Currently dav1d binding docs are not building as it is not having dav1d by defualt, we need to fix that.

https://docs.rs/crate/dav1d/0.6.0/builds/339431

**Comment by sdroege** [comment]
IIRC there's a way to detect if a build is running for docs.rs. Could make it build the C library in that case then.

**Comment by sdroege** [comment]
But also docs.rs IIRC does not allow network access during build, so that won't help much.

**Comment by lu-zero** [comment]
that would require making a dav1d-src crate...
