### ISSUE TITLE
Q: Possibility of static linking with prebuilt dav1d

### ISSUE THREAD

**Issue by FlareFlo** [rust-av/dav1d-rs#87]
I'm not particularly familiar with the build process of dav1d, and would be interested if static linking is possible without building dav1d from source (requiring meson etc.)

**Comment by lu-zero** [comment]
We use `system-deps` so setting the right [env var](https://docs.rs/system-deps/latest/system_deps/#static-linking) should work.

**Comment by lu-zero** [comment]
I'd close it if you hadn't problem using the env vars to link it statically.
