### ISSUE TITLE
Improved safe wrapper?

### ISSUE THREAD

**Issue by philn** [rust-av/dav1d-rs#9]
Hi,

I've started working on https://github.com/philn/dav1d-rs which builds upon your -sys bindings to provide an API for the decoder. It's still the early stages but I wonder if you would like to collaborate on this? I'd be OK with deprecating or merging my crate here of course :)

**Comment by lu-zero** [comment]
Would be great having your crate here and leverage the the shared data-structures that are here already, if it isn't too much work for you.

If it is ok for you I'd add you to the org immediately.

**Comment by philn** [comment]
Yeah of course, I'll be happy to help :)

**Comment by philn** [comment]
I'll soon prepare a PR to merge my crate in the wrapper you started recently, thanks for adding me! :)

**Comment by lu-zero** [comment]
Thank you!

**Comment by philn** [comment]
Ok, let's close this now. We have the foundation of a safe wrapper, more changes will come later on :)
