### ISSUE TITLE
exit code: 0xc0000135, STATUS_DLL_NOT_FOUND

### ISSUE THREAD

**Issue by soupslurpr** [rust-av/dav1d-rs#91]
I'm using Windows 11, Rust 1.76.0 latest stable and MSVC.

I followed the instructions in the README and the program compiles fine, but crashes when running with exit code: 0xc0000135, STATUS_DLL_NOT_FOUND.

Reproduction:
```
fn main() {
    dav1d::Decoder::new().unwrap();
}
```

**Comment by soupslurpr** [comment]
Installing ffmpeg from vcpkg fixed it.

**Comment by sdroege** [comment]
That means that the dav1d DLL is not in your `PATH`.

**Comment by soupslurpr** [comment]
Okay, thanks. Could this information be added to the README?
