### ISSUE TITLE
Colorimetry information

### ISSUE THREAD

**Issue by philn** [rust-av/dav1d-rs#93]
I'd like to add colorimetry information in the GStreamer decoder based on these bindings. I started a patch, https://github.com/philn/dav1d-rs-1/commit/19ada132d2c8bf7fec0bef4d0a5500493cbfcdee ... early feedback is welcome :)

**Comment by philn** [comment]
cc @lu-zero @sdroege

**Comment by lu-zero** [comment]
there are the rust-av definition in [av-data](https://github.com/rust-av/rust-av/blob/master/data/src/pixel.rs) maybe they can be recycled/refined for the purpose?

**Comment by philn** [comment]
Yeah that sounds like a good idea, I'd rather reinvent the wheel once more :) Thanks for the suggestion, I'll try to submit a PR in the coming days.
